#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/harvester/rancherd/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/harvester/rancherd/pkg/version.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/rancherd-amd64 ./cmd/rancherd
CGO_ENABLED=0 GOARCH=arm64 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/rancherd-arm64 ./cmd/rancherd
